### ISSUE TITLE
Please remove the "ddev-get" topic from this repo

### ISSUE THREAD

**Issue by rfay** [mattocchi/ddev-db-mssql#3]
Hi - It looks like maybe this was an experiment that's unmaintained. 

Could you please remove the "ddev-get" topic from the repo so it's not discovered by the general public?

Thanks,
-Randy
DDEV Maintainer

**Comment by mattocchi** [comment]
Hi Randy,
The ddev-get topic has been eliminated.
While I'm not actively maintaining this repository, it functioned correctly during my testing phase with PHP and MS SQL Server drivers.

**Comment by rfay** [comment]
Thanks!

I'd be interested to know if there was a difference between this and the official https://github.com/ddev/ddev-sqlsrv

-Randy
